export const types = {

    authChecking: "[auth] Checking login state",
    authCheckingFinish: "[auth] Finish Checking login state",
    authStartLogin: "[auth] Start login",
    authLogin: "[auth] Login",
    authStartRegister: "[auth] Start register",
    authStartTokenRenew: "[auth] Start token renew",
    authLogout: "[auth] Logout",

    uiOpenModal: "[ui] open modal",
    uiCloseModal: "[ui] close modal",
    pageMoreOne: "[page] one more page",
    pageUserMoreOne: "[page] one more user page",
    newPost: "[post] new post",
    uiOpenDeleteModal: "[ui] open delete modal",
    uiCloseDeleteModal: "[ui] close delete modal",
    uiOpenCommentModal: "[ui] open comment modal",
    uiCloseCommentModal: "[ui] close comment modal",
    searchFailedLoaded: "[search] searcg failed",
    hasNextPage: "[post] has next page",

    postAddNew: "[Post] Add new",
    postUpdated: "[Post] post updated",
    postDeleted: "[Post] post deleted",
    postDeletedStore: "[Post] post store deleted",
    postLoaded: "[Post] Add loaded",
    postLoadedMore: "[Post] Add more loaded",
    postLoadedOne: "[Post] Add one loaded",
    postFailedLoaded: "[Post] Failed loaded",
    postDetailFailed: "[Post] Failed detail loaded",
    blogLogoutCleaning: "[Blog] clean blog logout",

    commentAddNew: "[Comment] Add new",
    activeComment: "[Comment] active comment",
    desactiveComment: "[Comment] desactive comment",
    commentUpdated: "[Comment] comment updated",
    commentDeleted: "[Comment] comment deleted",
}